### ISSUE TITLE
本地运行后，chrome 手机模式没有渲染？

### ISSUE THREAD

**Issue by paddylives** [icatjs/icatjs-micro-demo#1]
从思否过来的，看到文章中说支持 **支持移动端。由于去掉了 routerBase 的依赖，又支持端应用，天然解决了基座重造成的渲染问题，反复重定向造成的跳转问题** 但是PC端可以访问，换成移动端则页面没有任何节点渲染
![image](https://user-images.githubusercontent.com/75835983/104807985-9c9ca080-5815-11eb-99c2-b386c1401a15.png)

我个人的目的是想找到 一个域名访问兼容PC和移动端的最优解。

**Comment by valleykid** [comment]
@paddylives 不好意思，没太关注 issue，回复晚了。😂

demo 比较匆忙，配置中没有 `endType` 会默认 pc。你配置下 `endType` 为 none，就可以是自适应模式了，这样就可以支持所有端。当然如果想比较好地支持各种端，建议还是提供真正的端应用，不要使用响应式。

配置可以改成这样：

```js
[
  {
    name: 'seeconf',
    entry: 'https://seeconf2019.antfin.com/',
    rules: [{ rule: '/seeconf' }],
    rootVars: { routerBase: '/seeconf', endType: 'none' },
  },
  {
    name: 'juejin',
    entry: 'https://juejin.cn/',
    rules: [{ rule: '/juejin', layout: 'seeconf > /seeconf', container: '#guests', endType: 'none' }],
    ignoreFileRules: ['analytics.js'],
  },
  {
    name: 'koubei',
    entry: 'https://www.koubei.com/',
    rules: [{ rule: '/', endType: 'none' }],
  },
]
```

> PS: 口碑 pc 端会检测当前端，如果是移动端会有个重定向动作，会影响到微前端正常显示(因为已经发生跳转，不过这也说明了框架正常工作了)。如果是你的应用，这个重定向动作需要再定制下的。

**Comment by paddylives** [comment]
ok,好的，谢谢回答
